### ISSUE TITLE
Sound Volume

### ISSUE THREAD

**Issue by TianxSky** [oqyh/cs2-Connect-Disconnect-Sound#1]
It is kind of a ear rape is there any way to change the sound volume

**Comment by oqyh** [comment]
unfortunately now is no,
need to wait cssharp to update on
```
Sound.EmitSound(i, sound, entity, channel, level, attenuation, flags, **volume**, pitch, origin,
                        direction);
```
EmitSound is now on /Modules/Disabled/ once its enable i will add that 

https://github.com/roflmuffin/CounterStrikeSharp/blob/12523455c02736b605e5055b78536acf6a345c6d/managed/CounterStrikeSharp.API/Modules/Disabled/Sound/Sound.cs

your better solution is to find better sound on
https://github.com/oqyh/cs2-Connect-Disconnect-Sound/blob/main/sounds/sounds.txt

and test sound by in game console 
"**play <soundpath>**"
there is many sounds low and fit your server 


best of luck 
oqyh,

**Comment by oqyh** [comment]
ill close this issue 
add good low sound
