### ISSUE TITLE
Slow server frame:

### ISSUE THREAD

**Issue by asdfxD** [oqyh/cs2-Connect-Disconnect-Sound#2]
whenever someone connects to the server and the connect message prints in chat i got Slow server frame: notice. 

i disabled the plugin and everything is fine.

Edit: reloaded the plugin few hours later again and it starts again.

**Comment by oqyh** [comment]
> whenever someone connects to the server and the connect message prints in chat i got Slow server frame: notice.
> 
> i disabled the plugin and everything is fine.
> 
> Edit: reloaded the plugin few hours later again and it starts again.

that could be your vm nothing to do with plugin

**Comment by asdfxD** [comment]
nope, when i disable plugin the issue is gone, when reenable after hours, it starts again. its the plugin. i do not use vm.

**Comment by asdfxD** [comment]
only metamod + cssharp + CnD Sound.1.0.9, no other stuff. cpu is dedicated and runs with 4,3GHz.

at almost every player connect, no slow server frames without this plugin.

https://github.com/oqyh/cs2-Connect-Disconnect-Sound/assets/24253340/e30ebf7e-a311-4ba1-8bfd-800aca82c72b

**Comment by oqyh** [comment]
> only metamod + cssharp + CnD Sound.1.0.9, no other stuff. cpu is dedicated and runs with 4,3GHz.
> 
> at almost every player connect, no slow server frames without this plugin.
> 
>  slow.mp4

thx for video will check that

**Comment by oqyh** [comment]
> only metamod + cssharp + CnD Sound.1.0.9, no other stuff. cpu is dedicated and runs with 4,3GHz.
> 
> at almost every player connect, no slow server frames without this plugin.
> 
>  slow.mp4

dm me on disocrd ao i can test it 
oqyh

**Comment by oqyh** [comment]
> nope, when i disable plugin the issue is gone, when reenable after hours, it starts again. its the plugin. i do not use vm.

test it in local vm (windows) 
public vm lunix + windows
iv never face any issue
